import React from 'react'
import { View, Text, StyleSheet, TouchableOpacity, TouchableNativeFeedback, Platform, Dimensions } from 'react-native'
import Communications from 'react-native-communications'
import Ionicons from 'react-native-vector-icons/Ionicons'

import Card from '../../components/Card'
import Colors from '../../constants/Colors'


let TouchableComponent = TouchableOpacity
if (Platform.OS === 'android' && Platform.Version >= 21) {
  TouchableComponent = TouchableNativeFeedback
}

const FeedbackScreen = props => {
  return (
    <View style={styles.contentContainer}>
      <TouchableComponent
        style={styles.button}
        onPress={() => {
          Communications.email(
            [`${userEmail}`, `${recepientEmail}`]
            , null
            , null
            , 'Subject of the email'
            , 'This is autogenerated by the App')}} >

            <Card style={styles.card}>
              <View>
                <Ionicons
                  style={styles.icon}
                  name={Platform.OS === 'android' ? 'md-mail' : 'ios-mail'}
                  size={Dimensions.get('window').width / 100 * 20}
                  color={Colors.primary}
                />
              </View>
              <View>
                <Text style={styles.text}>Send us feedback</Text>
              </View>
            </Card>
      </TouchableComponent>
    </View>
  )
}

const styles = StyleSheet.create({
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  button: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    width: Dimensions.get('window').width / 100 * 50,
    height: Dimensions.get('window').width / 100 * 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    paddingBottom: 5,
  },
  text: {
    fontSize: 18,
  }
})

export default FeedbackScreen