import React from 'react'
import { View, Text, StyleSheet, Platform, TouchableOpacity, TouchableNativeFeedback, Dimensions } from 'react-native'
import Communications from 'react-native-communications'
import Ionicons from 'react-native-vector-icons/Ionicons'

import Card from './Card'
import Colors from '../constants/Colors'

let TouchableComponent = TouchableOpacity
if (Platform.OS === 'android' && Platform.Version >= 21) {
  TouchableComponent = TouchableNativeFeedback
}

const ParticipantsItem = props => {
  let phoneNumber = props.phoneNumber
  let recepientEmail = props.email
  let userEmail = ''

  return (
    <Card style={styles.card}>
      <View style={styles.contanctElement}>
        <Text style={styles.company}>{props.company}</Text>
      </View>
      <View style={styles.contanctElement}>
        <Text style={styles.text}>{props.firstName} {props.lastName}</Text>
      </View>
      <View style={styles.contanctElement}>
        <Text style={styles.text}>{props.country}</Text>
      </View>

      <TouchableComponent onPress={() => {
        Communications.phonecall(`${phoneNumber}`, true)
      }}>
        <View style={styles.buttonContainer}>
          <Ionicons
            name={Platform.OS === 'android' ? 'md-call' : 'ios-call'}
            size={Dimensions.get('window').width / 100 * 7}
            color={Colors.primary}
          />
          <Text style={styles.text}>{props.phoneNumber}</Text>
        </View>
      </TouchableComponent>


      <TouchableComponent onPress={() => {
        Communications.email(
          [`${userEmail}`, `${recepientEmail}`]
          , null
          , null
          , 'Subject of the email'
          , 'This is autogenerated by the App')
      }}>
        <View style={styles.buttonContainer}>
          <Ionicons
            name={Platform.OS === 'android' ? 'md-mail' : 'ios-mail'}
            size={Dimensions.get('window').width / 100 * 7}
            color={Colors.primary}
          />
          <Text style={styles.text}>{props.email}</Text>
        </View>
      </TouchableComponent>
    </Card>
  )
}

const styles = StyleSheet.create({
  card: {
    flex: 1,
    margin: 10,
    padding: 10
  },
  contanctsContainer: {
    flex: 1,
  },
  contanctElement: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-start'
  },
  company: {
    fontSize: 18,
    padding: 5,
    fontWeight: 'bold'
  },
  text: {
    paddingLeft: 15,
  },
  buttonContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingLeft: 15,
    padding: 5,
    borderColor: Colors.defaultText,
    borderBottomWidth: 1,
  }
})

export default ParticipantsItem


